name: 'ðŸ“œ Check Commit Messages'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:    
      - 'master'

jobs:
  check-commit-messages:
    runs-on: ubuntu-24.04
    steps:
      - name: 'ðŸ“œ Check commit messages format'
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[^!]+: [A-Za-z]+.+ .+$'
          flags: 'gm'
          error: 'Commit subject line must match the following pattern: <scope>: <description>'
          excludeTitle: 'false'
          excludeDescription: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: 'ðŸ“œ Check commit messages length'
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[^#].{10,78}$'
          error: 'Commit subject line maximum line length of 78 characters is exceeded.'
          excludeTitle: 'false'
          excludeDescription: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
